[package]
name = "host"
description = "std CLI host for tiny-infer: file loading, tokenizer, command line"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "tiny-infer"
path = "src/main.rs"

[dependencies]
bytemuck = "1.25.0"
engine = { path = "../engine" }
llama = { path = "../llama" }
seq2seq = { path = "../seq2seq" }
humansize = "2.1.3"
rand = "0.10.1"
thousands = "0.2.0"
